version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    commit-message:
      include: scope
      prefix: chore

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    commit-message:
      include: scope
      prefix: ci
